server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy a la API
    location /api/ {
        proxy_pass http://api:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Acceso a la bandeja de correos (MailHog)
    location /mail/ {
        proxy_pass http://mail:8025/;
        proxy_set_header Host $host;
    }
}
